# Generated by Django 5.2.6 on 2025-10-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
